services:
  app:
    image: frontend-dev
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:8080/api
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: app
 
  server:
    env_file:
      - ./backend/.env
    image: backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: server
 
  reverse-proxy:
    image: nginx:1.29-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server
    container_name: reverse-proxy
 
volumes:
  node_modules:
