services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/
 
  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: server
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
        #- MONGO_URL=mongodb://mongo:27017/the_database
 
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: mongo
 
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis
 
  reverse-proxy:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server
    container_name: reverse-proxy
 
volumes:
  mongo_data:
  node_modules:
